scalar Date
scalar Cursor

type PageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor: Cursor
  endCursor: Cursor
  totalPageCount: Int
}

input GetUrlMetadataInput {
  url: String!
}

type Metadata {
  url: String!
  title: String
}

type Mutation {
  getUrlMetadata(input: GetUrlMetadataInput!): Metadata
}