enum Role {
  ENGINEERING
  DESIGNER
  PRODUCT
  OPERATIONS
  SALES
  MARKETING
  FOUNDER
  ANGEL_INVESTOR
  VENTURE_CAPITAL
}

enum Market {
  SOCIAL_MEDIA
  MEDIA
  HEALTH_CARE
  GAMES
  CRYPTO
  LOGISTICS
  HUMAN_RESOURCE
  ANALYTICS
  EDUCATION
  SECURITY
  FASHION
  FITNESS
  FOOD
  REAL_ESTATE
  E_COMMERCE
  AD_TECH
  AI
  DEVELOPER_TOOL
  PRODUCTIVITY
  WEARABLES
  VIRTUAL_REALITY
  COMSUMER
  DATABASES
  FINANCE
  TRAVEL
}

type Profile {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  email: String!
  username: String!
  fullname: String
  roles: [Role!]!
  markets: [Market!]!
  avatarUrl: String
  website: String
  linkedin: String
  facebook: String
  twitter: String
  github: String

  # posts: [Post!]!
  # comments: [Comment!]!
  # votes: [Vote!]!
}

type ProfileEdges {
  cursor: Cursor!
  node: Profile!
}

type ProfileConnection {
  edges: [ProfileEdges!]!
  pageInfo: PageInfo!
}

input ProfileFilter {
  roles: [Role!]
  markets: [Market!]
}

type Query {
  profile(id: ID!): Profile

  profiles(
    first: Int,
    after: Cursor,
    last: Int,
    before: Cursor,
    filter: ProfileFilter
  ): ProfileConnection!
}

input UpdateProfileMutationInput {
  id: ID!
  username: String
  fullname: String
  roles: [Role!]!
  markets: [Market!]!
  avatarUrl: String
  website: String
  linkedin: String
  facebook: String
  twitter: String
  github: String
}

type Mutation {
  updateProfile(input: UpdateProfileMutationInput!): Profile
}