scalar Date
scalar Cursor

enum OrderByDirection {
  AscNullsFirst
  AscNullsLast
  DescNullsFirst
  DescNullsLast
}

type Profile {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  username: String!
  avatarUrl: String
  website: String

  # posts: [Post!]!
  # comments: [Comment!]!
  # votes: [Vote!]!
}

type Post {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  posterId: ID!
  title: String!
  url: String
  content: String
  commentCount: Int!
  voteCount: Int!
  viewCount: Int!
  rankingScore: Int!

  poster: Profile
  comments: [Comment!]!
  votes: [Vote!]!
}

type Vote {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  postId: ID!
  voterId: ID!

  # post: Post!
  # voter: Profile!
}

type Comment {
  id: ID!
  createdAt: Date!
  updatedAt: Date!
  postId: ID!
  commenterId: ID!
  content: String!

  # post: Post!
  # commenter: Profile!
}

type PageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor: Cursor
  endCursor: Cursor
  totalPageCount: Int
}

type PostEdges {
  cursor: Cursor!
  node: Post!
}

type PostConnection {
  edges: [PostEdges!]!
  pageInfo: PageInfo!
}

input CreatePostMutationInput {
  posterId: ID!
  title: String!
  url: String
  content: String
}

input CreateVoteMutationInput {
  postId: ID!
  voterId: ID!
}

input CreateCommentMutationInput {
  postId: ID!
  commenterId: ID!
  content: String!
}

input PostFilter {
  title: String
}

input PostOrderBy {
  createdAt: OrderByDirection
  rankingScore: OrderByDirection
}

type Query {
  posts(
    first: Int,
    after: Cursor,
    last: Int,
    before: Cursor
  ): PostConnection!
}

type Mutation {
  createPost(input: CreatePostMutationInput!): Post!
  createVote(input: CreateVoteMutationInput!): Vote!
  createComment(input: CreateCommentMutationInput!): Comment!
}

