-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ENGINEERING', 'DESIGNER', 'PRODUCT', 'OPERATIONS', 'SALES', 'MARKETING', 'FOUNDER', 'ANGEL_INVESTOR', 'VENTURE_CAPITAL');

-- CreateEnum
CREATE TYPE "Market" AS ENUM ('SOCIAL_MEDIA', 'MEDIA', 'HEALTH_CARE', 'GAMES', 'CRYPTO', 'LOGISTICS', 'HUMAN_RESOURCE', 'ANALYTICS', 'EDUCATION', 'SECURITY', 'FASHION', 'FITNESS', 'FOOD', 'REAL_ESTATE', 'E_COMM', 'TRAVEL', 'AD_TECH', 'AI', 'DEVELOPER_TOOL', 'PRODUCTIVITY', 'WEARABLES', 'VIRTUAL_REALITY', 'COMSUMER', 'DATABASES', 'FINANCE');

-- AlterTable
ALTER TABLE "profiles" ADD COLUMN     "markets" "Market"[],
ADD COLUMN     "roles" "Role"[];
