-- AlterTable
ALTER TABLE "profiles" ADD COLUMN     "fullname" VARCHAR,
ALTER COLUMN "avatar_url" SET DATA TYPE VARCHAR,
ALTER COLUMN "website" SET DATA TYPE VARCHAR,
ALTER COLUMN "facebook" SET DATA TYPE VARCHAR,
ALTER COLUMN "github" SET DATA TYPE VARCHAR,
ALTER COLUMN "linkedin" SET DATA TYPE VARCHAR,
ALTER COLUMN "twitter" SET DATA TYPE VARCHAR;
